### ISSUE TITLE
Chapter 9, Page 145 - $\ with print and say

### ISSUE THREAD

**Issue by revhippie** [chromatic/modern_perl_book#240]
> Perl also uses any value of $\ as the final argument to print or say.

Well, sort of.  `say` does an implicit `{ local $\ = "\n" }`, doesn't it?  Forgive my Windows-style calling:

    C:\>perl -E "$\ = qq(ook ook\n); print 'hello'; say 'world';"
    helloook ook
    world

Immediately after this:

> Thus these two lines of code produce the same result:
>    `my @princes = qw( Corwin Eric Random ... );`
>    `print @princes;`
>    `print join( $,, @princes ) . $\;`

That's only true because `$\` is empty.  If you assign something to `$\`, it gets printed once for the first print, and twice for the second (one explicitly, one implicitly).

**Comment by chromatic** [comment]
Thanks, clarified in bdc1577.
