### ISSUE TITLE
Chapter 9, Page 138 - cmp_ok argument order

### ISSUE THREAD

**Issue by revhippie** [chromatic/modern_perl_book#241]
> `cmp_ok( 100, $cur_balance, '<=', 'I should have at least $100' );`
> `cmp_ok( $monkey, $ape, '==', 'Simian numifications should agree' );`

The comparator should go between the items being compared; from Test::More docs:

    cmp_ok( $got, $op, $expected, $test_name );

**Comment by chromatic** [comment]
Thanks, fixed!
